#!/bin/bash

# Fail early if there's an issue
set -e

# Tree to see the working directory's contents
#find . -type d -print | sed -e 's;[^/]*/;|____;g;s;____|;  |;g'
find . | sort | sed -e 's;[^/]*/;  |;g;s;|; ├──;'

# When .cache files are created, they need to know where HOME is to write there.
# In this case, that should be the HTCondor scratch dir the job is executing in.
export HOME=$(pwd)

# However this wrapper is set up, the EP will be handed a list of Snakemake arguments
# that were generated by Snakemake at the AP. Those define exactly which step/rule to run
# and with which parameters. Those args must be passed back to Snakemake here to run
# that step.
snakemake "$@"
